### ISSUE TITLE
@apply issue in component

### ISSUE THREAD

**Issue by geoffreyrichey** [ky-is/vue-cli-plugin-tailwind#2]
After installing the plugin using Vue CLI, inline class names work as expected but trying to use @apply with the shadowLookup I get the following error:

(12:5) `@apply` cannot be used with `.container` because `.container` either cannot be found, or it's actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.container` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

```
<template>
    <div class="main">
        <div class="border border-grey p-3 rounded">
            <!-- Style applies fine inline -->
        </div>
    </div>
</template>

<style lang="postcss" scoped>
    .main {
        @apply container mx-auto flex justify-center;
    }
</style>
```

**Comment by geoffreyrichey** [comment]
Solved using

```
<style lang="postcss" scoped>

    @tailwind preflight;

    .main {
        @apply absolute pin flex justify-center items-center
    }

    @tailwind utilities;

</style>
```

Is this the correct approach? Had to really search around to find this, might be helpful to specify on your docs.

**Comment by ky-is** [comment]
`@apply` has pretty strict rules for how it can be used unfortunately. According to https://github.com/tailwindcss/tailwindcss/issues/298, it doesn't work with Tailwind's `.container` plugin, by design.

Note that your solution should be simplifiable to:
```vue
<style lang="postcss" scoped>
    .main {
        @apply absolute pin flex justify-center items-center;
    }
</style>
```
As you're no longer depending on `@apply`ing the `.container` class. 

If you want to `@apply` custom classes, the best way I know of is to inline them into the component so that they're visible to `@apply`:
```vue
<style lang="postcss" scoped>
    .container {
        @apply absolute pin;
    }
    .main {
        @apply container;
    }
</style>
```
You can use [postcss-import](https://github.com/postcss/postcss-import) to inline your imports, which allows you to reuse these class definitions. That functionality might be worth including by default, I'll have to experiment with that.

Thanks!

**Comment by geoffreyrichey** [comment]
Thanks! I'm able to get things working now.
